server:
  port: 8282
  servlet:
    context-path: /api_001
spring:
  application:
    name: coffee-brace
#Data source
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cofbradb
    username: viola
    password: violapassw

  liquibase:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cofbradb
    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.xml
    user: viola
    password: violapassw
    change-log: classpath:db/db.changelog-master.yaml

  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
   # database-platform: org.hibernate.dialect.PostgreSQLDialect  HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
    hibernate:
      ddl-auto: validate

jwt:
  token:
    secret: jwtappdev
    expired: 600000